### ISSUE TITLE
Trades with same sell date can result in an adjustment and a loss

### ISSUE THREAD

**Issue by Gilby216** [bbreslauer/wash-sale-tracker#5]
I haven't found any official documentation saying this is for sure not allowed by the IRS but it seems unlikely that it is. The following two trades result in one of the ending lots having both an adjustment and a loss...

Num Shares,Symbol,Description,Buy Date,Adjusted Buy Date,Basis,Adjusted Basis,Sell Date,Proceeds,Adjustment Code,Adjustment,Form Position,Buy Lot,Replacement For,Is Replacement,Loss Processed
2,GOOG,GOOG,2/25/2014,,10000,,2/28/2014,5000,,,,,,,
5,GOOG,GOOG,2/25/2014,,25000,,2/28/2014,12500,,,,,,,

What it looks like is happening is that the starting lot has a loss and is washed into part of the other lot. Then the remaining part of the 2nd loss looks for a potential replacement and finds the first lot. To me this appears fine and legal. However, since the loss on the first lot was already processed, the new additional basis from the replacement isn't retroactively applied through to the replacement trade. 

TBH, I'm not 100% sure what the correct result is or how to handle this type of situation, but in this case one quick way to get a result that doesn't have the issue is to swap the starting position of the trades.

**Comment by bbreslauer** [comment]
Hmm, that's interesting. I'd only ever done this with the larger lot first, I guess. It's not good that it's based on the ordering of the purchases, though, so I'll think about how to make this consistent.

IANACPA, but I also don't think that the IRS has clarified how this would work. You could always request a ruling from them if you wanted :) But one other option is to just combine them into one line. I doubt the IRS would really care; the outcome isn't really any different either way.

**Comment by bbreslauer** [comment]
Fixed in c1c1cd33d8ece8e0df3ba68dc7264db11399c626
